/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPNOW_ESPNOW_BRIDGE_PB_H_INCLUDED
#define PB_ESPNOW_ESPNOW_BRIDGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _espnow_lr_BridgeHello {
    pb_callback_t bridge_mac;
    uint32_t max_peers;
    pb_callback_t version;
    uint32_t max_inflight;
} espnow_lr_BridgeHello;

typedef struct _espnow_lr_RadioFrame {
    pb_callback_t src_mac;
    pb_callback_t raw_frame;
    bool psk_tag_valid;
    int32_t rssi;
    uint32_t timestamp_ms;
} espnow_lr_RadioFrame;

typedef struct _espnow_lr_RadioSend {
    pb_callback_t dst_mac;
    pb_callback_t raw_frame;
    uint32_t seq;
} espnow_lr_RadioSend;

typedef struct _espnow_lr_SendResult {
    uint32_t seq;
    bool success;
    pb_callback_t error;
} espnow_lr_SendResult;

typedef struct _espnow_lr_BridgeStatus {
    int32_t wifi_rssi;
    uint32_t uptime_s;
    uint32_t free_heap;
    uint32_t peers_connected;
    uint32_t rx_queue_fill;
} espnow_lr_BridgeStatus;

typedef struct _espnow_lr_BridgeMessage {
    pb_size_t which_payload;
    union {
        espnow_lr_BridgeHello hello;
        espnow_lr_RadioFrame frame;
        espnow_lr_RadioSend send;
        espnow_lr_SendResult result;
        espnow_lr_BridgeStatus status;
    } payload;
} espnow_lr_BridgeMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define espnow_lr_BridgeHello_init_default       {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define espnow_lr_RadioFrame_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define espnow_lr_RadioSend_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define espnow_lr_SendResult_init_default        {0, 0, {{NULL}, NULL}}
#define espnow_lr_BridgeStatus_init_default      {0, 0, 0, 0, 0}
#define espnow_lr_BridgeMessage_init_default     {0, {espnow_lr_BridgeHello_init_default}}
#define espnow_lr_BridgeHello_init_zero          {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define espnow_lr_RadioFrame_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define espnow_lr_RadioSend_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define espnow_lr_SendResult_init_zero           {0, 0, {{NULL}, NULL}}
#define espnow_lr_BridgeStatus_init_zero         {0, 0, 0, 0, 0}
#define espnow_lr_BridgeMessage_init_zero        {0, {espnow_lr_BridgeHello_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define espnow_lr_BridgeHello_bridge_mac_tag     1
#define espnow_lr_BridgeHello_max_peers_tag      2
#define espnow_lr_BridgeHello_version_tag        3
#define espnow_lr_BridgeHello_max_inflight_tag   4
#define espnow_lr_RadioFrame_src_mac_tag         1
#define espnow_lr_RadioFrame_raw_frame_tag       2
#define espnow_lr_RadioFrame_psk_tag_valid_tag   3
#define espnow_lr_RadioFrame_rssi_tag            4
#define espnow_lr_RadioFrame_timestamp_ms_tag    5
#define espnow_lr_RadioSend_dst_mac_tag          1
#define espnow_lr_RadioSend_raw_frame_tag        2
#define espnow_lr_RadioSend_seq_tag              3
#define espnow_lr_SendResult_seq_tag             1
#define espnow_lr_SendResult_success_tag         2
#define espnow_lr_SendResult_error_tag           3
#define espnow_lr_BridgeStatus_wifi_rssi_tag     1
#define espnow_lr_BridgeStatus_uptime_s_tag      2
#define espnow_lr_BridgeStatus_free_heap_tag     3
#define espnow_lr_BridgeStatus_peers_connected_tag 4
#define espnow_lr_BridgeStatus_rx_queue_fill_tag 5
#define espnow_lr_BridgeMessage_hello_tag        1
#define espnow_lr_BridgeMessage_frame_tag        2
#define espnow_lr_BridgeMessage_send_tag         3
#define espnow_lr_BridgeMessage_result_tag       4
#define espnow_lr_BridgeMessage_status_tag       5

/* Struct field encoding specification for nanopb */
#define espnow_lr_BridgeHello_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    bridge_mac,        1) \
X(a, STATIC,   SINGULAR, UINT32,   max_peers,         2) \
X(a, CALLBACK, SINGULAR, STRING,   version,           3) \
X(a, STATIC,   SINGULAR, UINT32,   max_inflight,      4)
#define espnow_lr_BridgeHello_CALLBACK pb_default_field_callback
#define espnow_lr_BridgeHello_DEFAULT NULL

#define espnow_lr_RadioFrame_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    src_mac,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    raw_frame,         2) \
X(a, STATIC,   SINGULAR, BOOL,     psk_tag_valid,     3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      5)
#define espnow_lr_RadioFrame_CALLBACK pb_default_field_callback
#define espnow_lr_RadioFrame_DEFAULT NULL

#define espnow_lr_RadioSend_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    dst_mac,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    raw_frame,         2) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               3)
#define espnow_lr_RadioSend_CALLBACK pb_default_field_callback
#define espnow_lr_RadioSend_DEFAULT NULL

#define espnow_lr_SendResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, CALLBACK, SINGULAR, STRING,   error,             3)
#define espnow_lr_SendResult_CALLBACK pb_default_field_callback
#define espnow_lr_SendResult_DEFAULT NULL

#define espnow_lr_BridgeStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    wifi_rssi,         1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          2) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap,         3) \
X(a, STATIC,   SINGULAR, UINT32,   peers_connected,   4) \
X(a, STATIC,   SINGULAR, UINT32,   rx_queue_fill,     5)
#define espnow_lr_BridgeStatus_CALLBACK NULL
#define espnow_lr_BridgeStatus_DEFAULT NULL

#define espnow_lr_BridgeMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hello,payload.hello),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,frame,payload.frame),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send,payload.send),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,result,payload.result),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   5)
#define espnow_lr_BridgeMessage_CALLBACK NULL
#define espnow_lr_BridgeMessage_DEFAULT NULL
#define espnow_lr_BridgeMessage_payload_hello_MSGTYPE espnow_lr_BridgeHello
#define espnow_lr_BridgeMessage_payload_frame_MSGTYPE espnow_lr_RadioFrame
#define espnow_lr_BridgeMessage_payload_send_MSGTYPE espnow_lr_RadioSend
#define espnow_lr_BridgeMessage_payload_result_MSGTYPE espnow_lr_SendResult
#define espnow_lr_BridgeMessage_payload_status_MSGTYPE espnow_lr_BridgeStatus

extern const pb_msgdesc_t espnow_lr_BridgeHello_msg;
extern const pb_msgdesc_t espnow_lr_RadioFrame_msg;
extern const pb_msgdesc_t espnow_lr_RadioSend_msg;
extern const pb_msgdesc_t espnow_lr_SendResult_msg;
extern const pb_msgdesc_t espnow_lr_BridgeStatus_msg;
extern const pb_msgdesc_t espnow_lr_BridgeMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define espnow_lr_BridgeHello_fields &espnow_lr_BridgeHello_msg
#define espnow_lr_RadioFrame_fields &espnow_lr_RadioFrame_msg
#define espnow_lr_RadioSend_fields &espnow_lr_RadioSend_msg
#define espnow_lr_SendResult_fields &espnow_lr_SendResult_msg
#define espnow_lr_BridgeStatus_fields &espnow_lr_BridgeStatus_msg
#define espnow_lr_BridgeMessage_fields &espnow_lr_BridgeMessage_msg

/* Maximum encoded size of messages (where known) */
/* espnow_lr_BridgeHello_size depends on runtime parameters */
/* espnow_lr_RadioFrame_size depends on runtime parameters */
/* espnow_lr_RadioSend_size depends on runtime parameters */
/* espnow_lr_SendResult_size depends on runtime parameters */
/* espnow_lr_BridgeMessage_size depends on runtime parameters */
#define ESPNOW_LR_ESPNOW_BRIDGE_PB_H_MAX_SIZE    espnow_lr_BridgeStatus_size
#define espnow_lr_BridgeStatus_size              35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
