/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "espnow_bridge.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(espnow_lr_BridgeHello, espnow_lr_BridgeHello, AUTO)


PB_BIND(espnow_lr_RadioFrame, espnow_lr_RadioFrame, AUTO)


PB_BIND(espnow_lr_RadioSend, espnow_lr_RadioSend, AUTO)


PB_BIND(espnow_lr_SendResult, espnow_lr_SendResult, AUTO)


PB_BIND(espnow_lr_BridgeStatus, espnow_lr_BridgeStatus, AUTO)


PB_BIND(espnow_lr_BridgeMessage, espnow_lr_BridgeMessage, AUTO)



