/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "espnow_tree_runtime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(espnow_tree_runtime_v2_Envelope, espnow_tree_runtime_v2_Envelope, 2)


PB_BIND(espnow_tree_runtime_v2_AuthChallenge, espnow_tree_runtime_v2_AuthChallenge, AUTO)


PB_BIND(espnow_tree_runtime_v2_AuthResponse, espnow_tree_runtime_v2_AuthResponse, AUTO)


PB_BIND(espnow_tree_runtime_v2_AuthOk, espnow_tree_runtime_v2_AuthOk, AUTO)


PB_BIND(espnow_tree_runtime_v2_AuthFailed, espnow_tree_runtime_v2_AuthFailed, AUTO)


PB_BIND(espnow_tree_runtime_v2_ClientHello, espnow_tree_runtime_v2_ClientHello, AUTO)


PB_BIND(espnow_tree_runtime_v2_KnownRemoteSchema, espnow_tree_runtime_v2_KnownRemoteSchema, AUTO)


PB_BIND(espnow_tree_runtime_v2_FullSnapshot, espnow_tree_runtime_v2_FullSnapshot, AUTO)


PB_BIND(espnow_tree_runtime_v2_BridgeIdentity, espnow_tree_runtime_v2_BridgeIdentity, AUTO)


PB_BIND(espnow_tree_runtime_v2_BridgeCapabilities, espnow_tree_runtime_v2_BridgeCapabilities, AUTO)


PB_BIND(espnow_tree_runtime_v2_BridgeRuntime, espnow_tree_runtime_v2_BridgeRuntime, AUTO)


PB_BIND(espnow_tree_runtime_v2_RemoteSnapshot, espnow_tree_runtime_v2_RemoteSnapshot, 2)


PB_BIND(espnow_tree_runtime_v2_RemoteIdentity, espnow_tree_runtime_v2_RemoteIdentity, AUTO)


PB_BIND(espnow_tree_runtime_v2_RemoteRuntime, espnow_tree_runtime_v2_RemoteRuntime, AUTO)


PB_BIND(espnow_tree_runtime_v2_RemoteDescriptorSet, espnow_tree_runtime_v2_RemoteDescriptorSet, AUTO)


PB_BIND(espnow_tree_runtime_v2_EntityDescriptor, espnow_tree_runtime_v2_EntityDescriptor, AUTO)


PB_BIND(espnow_tree_runtime_v2_Option, espnow_tree_runtime_v2_Option, AUTO)


PB_BIND(espnow_tree_runtime_v2_CommandDescriptor, espnow_tree_runtime_v2_CommandDescriptor, AUTO)


PB_BIND(espnow_tree_runtime_v2_ArgumentDescriptor, espnow_tree_runtime_v2_ArgumentDescriptor, AUTO)


PB_BIND(espnow_tree_runtime_v2_EntityState, espnow_tree_runtime_v2_EntityState, AUTO)


PB_BIND(espnow_tree_runtime_v2_EventBatch, espnow_tree_runtime_v2_EventBatch, AUTO)


PB_BIND(espnow_tree_runtime_v2_Event, espnow_tree_runtime_v2_Event, 2)


PB_BIND(espnow_tree_runtime_v2_RemoteAvailabilityEvent, espnow_tree_runtime_v2_RemoteAvailabilityEvent, AUTO)


PB_BIND(espnow_tree_runtime_v2_RemoteStateEvent, espnow_tree_runtime_v2_RemoteStateEvent, AUTO)


PB_BIND(espnow_tree_runtime_v2_RemoteSchemaChangedEvent, espnow_tree_runtime_v2_RemoteSchemaChangedEvent, 2)


PB_BIND(espnow_tree_runtime_v2_RemoteMetadataChangedEvent, espnow_tree_runtime_v2_RemoteMetadataChangedEvent, 2)


PB_BIND(espnow_tree_runtime_v2_TopologyChangedEvent, espnow_tree_runtime_v2_TopologyChangedEvent, AUTO)


PB_BIND(espnow_tree_runtime_v2_BridgeHeartbeat, espnow_tree_runtime_v2_BridgeHeartbeat, AUTO)


PB_BIND(espnow_tree_runtime_v2_CommandRequest, espnow_tree_runtime_v2_CommandRequest, AUTO)


PB_BIND(espnow_tree_runtime_v2_CommandArgument, espnow_tree_runtime_v2_CommandArgument, AUTO)


PB_BIND(espnow_tree_runtime_v2_CommandResult, espnow_tree_runtime_v2_CommandResult, AUTO)


PB_BIND(espnow_tree_runtime_v2_ConfigCommandRequest, espnow_tree_runtime_v2_ConfigCommandRequest, AUTO)


PB_BIND(espnow_tree_runtime_v2_ConfigCommandResult, espnow_tree_runtime_v2_ConfigCommandResult, AUTO)


PB_BIND(espnow_tree_runtime_v2_Ping, espnow_tree_runtime_v2_Ping, AUTO)


PB_BIND(espnow_tree_runtime_v2_Pong, espnow_tree_runtime_v2_Pong, AUTO)


PB_BIND(espnow_tree_runtime_v2_Error, espnow_tree_runtime_v2_Error, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

