send_command:
  fields:
    remote_mac:
      required: true
      selector:
        text:
    object_id:
      required: true
      selector:
        text:
    command:
      required: true
      selector:
        text:
    value:
      required: false
      selector:
        text:
