# CMake generated Testfile for 
# Source directory: /home/ben/ai-hermes-agent/ESPLR_V2/tests
# Build directory: /home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(protocol_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/protocol_test")
set_tests_properties(protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;14;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(allowed_parents_config_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/allowed_parents_config_test")
set_tests_properties(allowed_parents_config_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;17;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(heartbeat_parent_mac_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/heartbeat_parent_mac_test")
set_tests_properties(heartbeat_parent_mac_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;20;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(packet_sizes_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/packet_sizes_test")
set_tests_properties(packet_sizes_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;24;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(parse_helpers_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/parse_helpers_test")
set_tests_properties(parse_helpers_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;28;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(counter_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/counter_test")
set_tests_properties(counter_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;32;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(fragment_assembly_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/fragment_assembly_test")
set_tests_properties(fragment_assembly_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;36;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(route_expiry_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/route_expiry_test")
set_tests_properties(route_expiry_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;40;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(join_status_codes_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/join_status_codes_test")
set_tests_properties(join_status_codes_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;44;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(state_machine_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/state_machine_test")
set_tests_properties(state_machine_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;48;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(session_eviction_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/session_eviction_test")
set_tests_properties(session_eviction_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;52;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(retry_backoff_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/retry_backoff_test")
set_tests_properties(retry_backoff_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;56;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(command_queue_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/command_queue_test")
set_tests_properties(command_queue_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;60;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(encryption_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/encryption_test")
set_tests_properties(encryption_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;67;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(hop_encoding_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/hop_encoding_test")
set_tests_properties(hop_encoding_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;71;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(mac_key_computation_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/mac_key_computation_test")
set_tests_properties(mac_key_computation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;75;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b4_bool_flags_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b4_bool_flags_test")
set_tests_properties(b4_bool_flags_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;79;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b6_fragment_interleaving_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b6_fragment_interleaving_test")
set_tests_properties(b6_fragment_interleaving_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;85;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b7_vtaskdelay_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b7_vtaskdelay_test")
set_tests_properties(b7_vtaskdelay_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;89;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b11_mqtt_starvation_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b11_mqtt_starvation_test")
set_tests_properties(b11_mqtt_starvation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;93;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b7b_error_handling_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b7b_error_handling_test")
set_tests_properties(b7b_error_handling_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;97;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b7c_boundary_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b7c_boundary_test")
set_tests_properties(b7c_boundary_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;101;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(b9b10_wait_backoff_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/b9b10_wait_backoff_test")
set_tests_properties(b9b10_wait_backoff_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;105;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
add_test(file_receiver_test "/home/ben/ai-hermes-agent/ESPLR_V2/tests/build_stage3/file_receiver_test")
set_tests_properties(file_receiver_test PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;120;add_test;/home/ben/ai-hermes-agent/ESPLR_V2/tests/CMakeLists.txt;0;")
