/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "esp_tree_runtime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esp_tree_runtime_v2_Envelope, esp_tree_runtime_v2_Envelope, 2)


PB_BIND(esp_tree_runtime_v2_AuthChallenge, esp_tree_runtime_v2_AuthChallenge, AUTO)


PB_BIND(esp_tree_runtime_v2_AuthResponse, esp_tree_runtime_v2_AuthResponse, AUTO)


PB_BIND(esp_tree_runtime_v2_AuthOk, esp_tree_runtime_v2_AuthOk, AUTO)


PB_BIND(esp_tree_runtime_v2_AuthFailed, esp_tree_runtime_v2_AuthFailed, AUTO)


PB_BIND(esp_tree_runtime_v2_ClientHello, esp_tree_runtime_v2_ClientHello, AUTO)


PB_BIND(esp_tree_runtime_v2_KnownRemoteSchema, esp_tree_runtime_v2_KnownRemoteSchema, AUTO)


PB_BIND(esp_tree_runtime_v2_FullSnapshot, esp_tree_runtime_v2_FullSnapshot, AUTO)


PB_BIND(esp_tree_runtime_v2_BridgeIdentity, esp_tree_runtime_v2_BridgeIdentity, AUTO)


PB_BIND(esp_tree_runtime_v2_BridgeCapabilities, esp_tree_runtime_v2_BridgeCapabilities, AUTO)


PB_BIND(esp_tree_runtime_v2_BridgeRuntime, esp_tree_runtime_v2_BridgeRuntime, AUTO)


PB_BIND(esp_tree_runtime_v2_RemoteSnapshot, esp_tree_runtime_v2_RemoteSnapshot, 2)


PB_BIND(esp_tree_runtime_v2_RemoteIdentity, esp_tree_runtime_v2_RemoteIdentity, AUTO)


PB_BIND(esp_tree_runtime_v2_RemoteRuntime, esp_tree_runtime_v2_RemoteRuntime, AUTO)


PB_BIND(esp_tree_runtime_v2_RemoteDescriptorSet, esp_tree_runtime_v2_RemoteDescriptorSet, AUTO)


PB_BIND(esp_tree_runtime_v2_EntityDescriptor, esp_tree_runtime_v2_EntityDescriptor, AUTO)


PB_BIND(esp_tree_runtime_v2_Option, esp_tree_runtime_v2_Option, AUTO)


PB_BIND(esp_tree_runtime_v2_CommandDescriptor, esp_tree_runtime_v2_CommandDescriptor, AUTO)


PB_BIND(esp_tree_runtime_v2_ArgumentDescriptor, esp_tree_runtime_v2_ArgumentDescriptor, AUTO)


PB_BIND(esp_tree_runtime_v2_EntityState, esp_tree_runtime_v2_EntityState, AUTO)


PB_BIND(esp_tree_runtime_v2_EventBatch, esp_tree_runtime_v2_EventBatch, AUTO)


PB_BIND(esp_tree_runtime_v2_Event, esp_tree_runtime_v2_Event, 2)


PB_BIND(esp_tree_runtime_v2_RemoteAvailabilityEvent, esp_tree_runtime_v2_RemoteAvailabilityEvent, AUTO)


PB_BIND(esp_tree_runtime_v2_RemoteStateEvent, esp_tree_runtime_v2_RemoteStateEvent, AUTO)


PB_BIND(esp_tree_runtime_v2_RemoteSchemaChangedEvent, esp_tree_runtime_v2_RemoteSchemaChangedEvent, 2)


PB_BIND(esp_tree_runtime_v2_RemoteMetadataChangedEvent, esp_tree_runtime_v2_RemoteMetadataChangedEvent, 2)


PB_BIND(esp_tree_runtime_v2_TopologyChangedEvent, esp_tree_runtime_v2_TopologyChangedEvent, AUTO)


PB_BIND(esp_tree_runtime_v2_BridgeHeartbeat, esp_tree_runtime_v2_BridgeHeartbeat, AUTO)


PB_BIND(esp_tree_runtime_v2_CommandRequest, esp_tree_runtime_v2_CommandRequest, AUTO)


PB_BIND(esp_tree_runtime_v2_CommandArgument, esp_tree_runtime_v2_CommandArgument, AUTO)


PB_BIND(esp_tree_runtime_v2_CommandResult, esp_tree_runtime_v2_CommandResult, AUTO)


PB_BIND(esp_tree_runtime_v2_ConfigCommandRequest, esp_tree_runtime_v2_ConfigCommandRequest, AUTO)


PB_BIND(esp_tree_runtime_v2_ConfigCommandResult, esp_tree_runtime_v2_ConfigCommandResult, AUTO)


PB_BIND(esp_tree_runtime_v2_Ping, esp_tree_runtime_v2_Ping, AUTO)


PB_BIND(esp_tree_runtime_v2_Pong, esp_tree_runtime_v2_Pong, AUTO)


PB_BIND(esp_tree_runtime_v2_Error, esp_tree_runtime_v2_Error, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

