/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESP_TREE_RUNTIME_V2_ESP_TREE_RUNTIME_PB_H_INCLUDED
#define PB_ESP_TREE_RUNTIME_V2_ESP_TREE_RUNTIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _esp_tree_runtime_v2_CommandStatus {
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_UNSPECIFIED = 0,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_ACCEPTED = 1,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_DELIVERED = 2,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_FAILED = 3,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_UNAVAILABLE = 4,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_UNSUPPORTED = 5,
    esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_TIMEOUT = 6
} esp_tree_runtime_v2_CommandStatus;

/* Struct definitions */
typedef struct _esp_tree_runtime_v2_AuthChallenge {
    pb_callback_t server_nonce;
    uint32_t min_version;
    uint32_t max_version;
    pb_callback_t protocol;
    pb_callback_t bridge_mac;
} esp_tree_runtime_v2_AuthChallenge;

typedef struct _esp_tree_runtime_v2_AuthResponse {
    pb_callback_t client_kind;
    pb_callback_t client_name;
    pb_callback_t client_nonce;
    pb_callback_t hmac_sha256;
} esp_tree_runtime_v2_AuthResponse;

typedef struct _esp_tree_runtime_v2_AuthFailed {
    pb_callback_t code;
    pb_callback_t message;
} esp_tree_runtime_v2_AuthFailed;

typedef struct _esp_tree_runtime_v2_ClientHello {
    bool request_full_snapshot;
    pb_callback_t integration_version;
    pb_callback_t known_remote_schemas;
} esp_tree_runtime_v2_ClientHello;

typedef struct _esp_tree_runtime_v2_KnownRemoteSchema {
    pb_callback_t remote_mac;
    pb_callback_t schema_hash;
} esp_tree_runtime_v2_KnownRemoteSchema;

typedef struct _esp_tree_runtime_v2_BridgeIdentity {
    pb_callback_t bridge_mac;
    pb_callback_t bridge_name;
    pb_callback_t friendly_name;
    pb_callback_t network_id;
    pb_callback_t manufacturer;
    pb_callback_t model;
    pb_callback_t project_name;
    pb_callback_t project_version;
    pb_callback_t firmware_build_date;
    pb_callback_t api_server;
} esp_tree_runtime_v2_BridgeIdentity;

typedef struct _esp_tree_runtime_v2_BridgeCapabilities {
    bool supports_runtime_v2;
    bool supports_commands;
    bool supports_schema_push;
    bool supports_state_push;
    bool supports_topology;
    bool supports_config_commands;
} esp_tree_runtime_v2_BridgeCapabilities;

typedef struct _esp_tree_runtime_v2_AuthOk {
    uint32_t negotiated_version;
    pb_callback_t server_name;
    bool has_bridge;
    esp_tree_runtime_v2_BridgeIdentity bridge;
    bool has_capabilities;
    esp_tree_runtime_v2_BridgeCapabilities capabilities;
} esp_tree_runtime_v2_AuthOk;

typedef struct _esp_tree_runtime_v2_BridgeRuntime {
    bool online;
    int32_t wifi_rssi;
    uint32_t uptime_s;
    uint32_t remote_count;
} esp_tree_runtime_v2_BridgeRuntime;

typedef struct _esp_tree_runtime_v2_FullSnapshot {
    bool has_bridge;
    esp_tree_runtime_v2_BridgeIdentity bridge;
    bool has_bridge_runtime;
    esp_tree_runtime_v2_BridgeRuntime bridge_runtime;
    pb_callback_t remotes;
    uint64_t snapshot_unix_ms;
} esp_tree_runtime_v2_FullSnapshot;

typedef struct _esp_tree_runtime_v2_RemoteIdentity {
    pb_callback_t remote_mac;
    pb_callback_t esphome_name;
    pb_callback_t friendly_name;
    pb_callback_t manufacturer;
    pb_callback_t model;
    pb_callback_t project_name;
    pb_callback_t project_version;
    pb_callback_t firmware_build_date;
    pb_callback_t firmware_md5;
    pb_callback_t schema_hash;
    uint32_t entity_count;
    pb_callback_t chip_name;
    bool can_relay;
    bool relay_enabled;
} esp_tree_runtime_v2_RemoteIdentity;

typedef struct _esp_tree_runtime_v2_RemoteRuntime {
    bool online;
    pb_callback_t bridge_mac;
    pb_callback_t parent_mac;
    uint32_t hops_to_bridge;
    int32_t rssi;
    uint32_t offline_s;
    uint64_t last_seen_unix_ms;
    pb_callback_t session_id;
    uint32_t last_tx_counter;
} esp_tree_runtime_v2_RemoteRuntime;

typedef struct _esp_tree_runtime_v2_RemoteDescriptorSet {
    pb_callback_t schema_hash;
    pb_callback_t entities;
} esp_tree_runtime_v2_RemoteDescriptorSet;

typedef struct _esp_tree_runtime_v2_RemoteSnapshot {
    bool has_identity;
    esp_tree_runtime_v2_RemoteIdentity identity;
    bool has_runtime;
    esp_tree_runtime_v2_RemoteRuntime runtime;
    bool has_descriptor_set;
    esp_tree_runtime_v2_RemoteDescriptorSet descriptor_set;
    pb_callback_t states;
} esp_tree_runtime_v2_RemoteSnapshot;

typedef struct _esp_tree_runtime_v2_Option {
    pb_callback_t key;
    pb_callback_t label;
} esp_tree_runtime_v2_Option;

typedef struct _esp_tree_runtime_v2_CommandDescriptor {
    pb_callback_t supported_commands;
    pb_callback_t arguments;
} esp_tree_runtime_v2_CommandDescriptor;

typedef struct _esp_tree_runtime_v2_EntityDescriptor {
    pb_callback_t object_id;
    pb_callback_t platform;
    pb_callback_t friendly_name;
    pb_callback_t icon;
    pb_callback_t device_class;
    pb_callback_t state_class;
    pb_callback_t unit_of_measurement;
    pb_callback_t entity_category;
    bool disabled_by_default;
    bool diagnostic;
    bool writable;
    pb_callback_t native_type;
    pb_callback_t options_json;
    pb_callback_t options;
    bool has_command;
    esp_tree_runtime_v2_CommandDescriptor command;
} esp_tree_runtime_v2_EntityDescriptor;

typedef struct _esp_tree_runtime_v2_ArgumentDescriptor {
    pb_callback_t name;
    pb_callback_t value_type;
    bool required;
    double min_value;
    double max_value;
    double step;
} esp_tree_runtime_v2_ArgumentDescriptor;

typedef struct _esp_tree_runtime_v2_EntityState {
    pb_callback_t object_id;
    bool available;
    uint64_t observed_unix_ms;
    pb_size_t which_value;
    union {
        bool bool_value;
        int64_t int_value;
        double float_value;
        pb_callback_t string_value;
        pb_callback_t bytes_value;
    } value;
} esp_tree_runtime_v2_EntityState;

typedef struct _esp_tree_runtime_v2_EventBatch {
    pb_callback_t events;
} esp_tree_runtime_v2_EventBatch;

typedef struct _esp_tree_runtime_v2_RemoteAvailabilityEvent {
    pb_callback_t remote_mac;
    bool online;
    pb_callback_t bridge_mac;
    pb_callback_t session_id;
    uint32_t tx_counter;
    uint64_t observed_unix_ms;
    int32_t rssi;
    uint32_t hops_to_bridge;
    pb_callback_t reason;
} esp_tree_runtime_v2_RemoteAvailabilityEvent;

typedef struct _esp_tree_runtime_v2_RemoteStateEvent {
    pb_callback_t remote_mac;
    pb_callback_t bridge_mac;
    pb_callback_t session_id;
    uint32_t tx_counter;
    pb_callback_t states;
    uint64_t observed_unix_ms;
} esp_tree_runtime_v2_RemoteStateEvent;

typedef struct _esp_tree_runtime_v2_RemoteSchemaChangedEvent {
    pb_callback_t remote_mac;
    pb_callback_t bridge_mac;
    pb_callback_t session_id;
    pb_callback_t old_schema_hash;
    bool has_snapshot;
    esp_tree_runtime_v2_RemoteSnapshot snapshot;
} esp_tree_runtime_v2_RemoteSchemaChangedEvent;

typedef struct _esp_tree_runtime_v2_RemoteMetadataChangedEvent {
    bool has_identity;
    esp_tree_runtime_v2_RemoteIdentity identity;
    bool has_runtime;
    esp_tree_runtime_v2_RemoteRuntime runtime;
} esp_tree_runtime_v2_RemoteMetadataChangedEvent;

typedef struct _esp_tree_runtime_v2_TopologyChangedEvent {
    pb_callback_t remote_mac;
    pb_callback_t bridge_mac;
    pb_callback_t parent_mac;
    uint32_t hops_to_bridge;
    int32_t rssi;
    uint64_t observed_unix_ms;
} esp_tree_runtime_v2_TopologyChangedEvent;

typedef struct _esp_tree_runtime_v2_BridgeHeartbeat {
    pb_callback_t bridge_mac;
    uint64_t bridge_unix_ms;
    uint32_t uptime_s;
} esp_tree_runtime_v2_BridgeHeartbeat;

typedef struct _esp_tree_runtime_v2_Event {
    pb_size_t which_kind;
    union {
        esp_tree_runtime_v2_BridgeHeartbeat bridge_heartbeat;
        esp_tree_runtime_v2_RemoteAvailabilityEvent remote_availability;
        esp_tree_runtime_v2_RemoteStateEvent remote_state;
        esp_tree_runtime_v2_RemoteSchemaChangedEvent remote_schema_changed;
        esp_tree_runtime_v2_RemoteMetadataChangedEvent remote_metadata_changed;
        esp_tree_runtime_v2_TopologyChangedEvent topology_changed;
    } kind;
} esp_tree_runtime_v2_Event;

typedef struct _esp_tree_runtime_v2_CommandRequest {
    pb_callback_t remote_mac;
    pb_callback_t object_id;
    pb_callback_t command;
    pb_callback_t args;
} esp_tree_runtime_v2_CommandRequest;

typedef struct _esp_tree_runtime_v2_CommandArgument {
    pb_callback_t name;
    pb_size_t which_value;
    union {
        bool bool_value;
        int64_t int_value;
        double float_value;
        pb_callback_t string_value;
    } value;
} esp_tree_runtime_v2_CommandArgument;

typedef struct _esp_tree_runtime_v2_CommandResult {
    pb_callback_t remote_mac;
    pb_callback_t object_id;
    pb_callback_t command;
    pb_callback_t bridge_mac;
    pb_callback_t session_id;
    esp_tree_runtime_v2_CommandStatus status;
    pb_callback_t error_code;
    pb_callback_t error_message;
} esp_tree_runtime_v2_CommandResult;

typedef struct _esp_tree_runtime_v2_ConfigCommandRequest {
    pb_callback_t remote_mac;
    pb_callback_t command;
    uint32_t interval_seconds;
    pb_callback_t parent_mac;
    bool clear_parent;
    bool relay_enable;
} esp_tree_runtime_v2_ConfigCommandRequest;

typedef struct _esp_tree_runtime_v2_ConfigCommandResult {
    pb_callback_t remote_mac;
    pb_callback_t command;
    pb_callback_t bridge_mac;
    pb_callback_t session_id;
    esp_tree_runtime_v2_CommandStatus status;
    pb_callback_t error_code;
    pb_callback_t error_message;
} esp_tree_runtime_v2_ConfigCommandResult;

typedef struct _esp_tree_runtime_v2_Ping {
    uint64_t monotonic_ms;
} esp_tree_runtime_v2_Ping;

typedef struct _esp_tree_runtime_v2_Pong {
    uint64_t monotonic_ms;
} esp_tree_runtime_v2_Pong;

typedef struct _esp_tree_runtime_v2_Error {
    pb_callback_t code;
    pb_callback_t message;
} esp_tree_runtime_v2_Error;

typedef struct _esp_tree_runtime_v2_Envelope {
    pb_callback_t request_id;
    uint32_t api_version;
    pb_size_t which_msg;
    union {
        esp_tree_runtime_v2_AuthChallenge auth_challenge;
        esp_tree_runtime_v2_AuthResponse auth_response;
        esp_tree_runtime_v2_AuthOk auth_ok;
        esp_tree_runtime_v2_AuthFailed auth_failed;
        esp_tree_runtime_v2_ClientHello client_hello;
        esp_tree_runtime_v2_FullSnapshot full_snapshot;
        esp_tree_runtime_v2_EventBatch event_batch;
        esp_tree_runtime_v2_CommandRequest command_request;
        esp_tree_runtime_v2_CommandResult command_result;
        esp_tree_runtime_v2_ConfigCommandRequest config_command_request;
        esp_tree_runtime_v2_ConfigCommandResult config_command_result;
        esp_tree_runtime_v2_Ping ping;
        esp_tree_runtime_v2_Pong pong;
        esp_tree_runtime_v2_Error error;
    } msg;
} esp_tree_runtime_v2_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _esp_tree_runtime_v2_CommandStatus_MIN esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_UNSPECIFIED
#define _esp_tree_runtime_v2_CommandStatus_MAX esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_TIMEOUT
#define _esp_tree_runtime_v2_CommandStatus_ARRAYSIZE ((esp_tree_runtime_v2_CommandStatus)(esp_tree_runtime_v2_CommandStatus_COMMAND_STATUS_TIMEOUT+1))































#define esp_tree_runtime_v2_CommandResult_status_ENUMTYPE esp_tree_runtime_v2_CommandStatus


#define esp_tree_runtime_v2_ConfigCommandResult_status_ENUMTYPE esp_tree_runtime_v2_CommandStatus





/* Initializer values for message structs */
#define esp_tree_runtime_v2_Envelope_init_default {{{NULL}, NULL}, 0, 0, {esp_tree_runtime_v2_AuthChallenge_init_default}}
#define esp_tree_runtime_v2_AuthChallenge_init_default {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_AuthResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_AuthOk_init_default {0, {{NULL}, NULL}, false, esp_tree_runtime_v2_BridgeIdentity_init_default, false, esp_tree_runtime_v2_BridgeCapabilities_init_default}
#define esp_tree_runtime_v2_AuthFailed_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ClientHello_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_KnownRemoteSchema_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_FullSnapshot_init_default {false, esp_tree_runtime_v2_BridgeIdentity_init_default, false, esp_tree_runtime_v2_BridgeRuntime_init_default, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_BridgeIdentity_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_BridgeCapabilities_init_default {0, 0, 0, 0, 0, 0}
#define esp_tree_runtime_v2_BridgeRuntime_init_default {0, 0, 0, 0}
#define esp_tree_runtime_v2_RemoteSnapshot_init_default {false, esp_tree_runtime_v2_RemoteIdentity_init_default, false, esp_tree_runtime_v2_RemoteRuntime_init_default, false, esp_tree_runtime_v2_RemoteDescriptorSet_init_default, {{NULL}, NULL}}
#define esp_tree_runtime_v2_RemoteIdentity_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_RemoteRuntime_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_RemoteDescriptorSet_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_EntityDescriptor_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, esp_tree_runtime_v2_CommandDescriptor_init_default}
#define esp_tree_runtime_v2_Option_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_CommandDescriptor_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ArgumentDescriptor_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define esp_tree_runtime_v2_EntityState_init_default {{{NULL}, NULL}, 0, 0, 0, {0}}
#define esp_tree_runtime_v2_EventBatch_init_default {{{NULL}, NULL}}
#define esp_tree_runtime_v2_Event_init_default {0, {esp_tree_runtime_v2_BridgeHeartbeat_init_default}}
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}}
#define esp_tree_runtime_v2_RemoteStateEvent_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, esp_tree_runtime_v2_RemoteSnapshot_init_default}
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_init_default {false, esp_tree_runtime_v2_RemoteIdentity_init_default, false, esp_tree_runtime_v2_RemoteRuntime_init_default}
#define esp_tree_runtime_v2_TopologyChangedEvent_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define esp_tree_runtime_v2_BridgeHeartbeat_init_default {{{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_CommandRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_CommandArgument_init_default {{{NULL}, NULL}, 0, {0}}
#define esp_tree_runtime_v2_CommandResult_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _esp_tree_runtime_v2_CommandStatus_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ConfigCommandRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_ConfigCommandResult_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _esp_tree_runtime_v2_CommandStatus_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_Ping_init_default {0}
#define esp_tree_runtime_v2_Pong_init_default {0}
#define esp_tree_runtime_v2_Error_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_Envelope_init_zero {{{NULL}, NULL}, 0, 0, {esp_tree_runtime_v2_AuthChallenge_init_zero}}
#define esp_tree_runtime_v2_AuthChallenge_init_zero {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_AuthResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_AuthOk_init_zero  {0, {{NULL}, NULL}, false, esp_tree_runtime_v2_BridgeIdentity_init_zero, false, esp_tree_runtime_v2_BridgeCapabilities_init_zero}
#define esp_tree_runtime_v2_AuthFailed_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ClientHello_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_KnownRemoteSchema_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_FullSnapshot_init_zero {false, esp_tree_runtime_v2_BridgeIdentity_init_zero, false, esp_tree_runtime_v2_BridgeRuntime_init_zero, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_BridgeIdentity_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_BridgeCapabilities_init_zero {0, 0, 0, 0, 0, 0}
#define esp_tree_runtime_v2_BridgeRuntime_init_zero {0, 0, 0, 0}
#define esp_tree_runtime_v2_RemoteSnapshot_init_zero {false, esp_tree_runtime_v2_RemoteIdentity_init_zero, false, esp_tree_runtime_v2_RemoteRuntime_init_zero, false, esp_tree_runtime_v2_RemoteDescriptorSet_init_zero, {{NULL}, NULL}}
#define esp_tree_runtime_v2_RemoteIdentity_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_RemoteRuntime_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_RemoteDescriptorSet_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_EntityDescriptor_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, esp_tree_runtime_v2_CommandDescriptor_init_zero}
#define esp_tree_runtime_v2_Option_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_CommandDescriptor_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ArgumentDescriptor_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define esp_tree_runtime_v2_EntityState_init_zero {{{NULL}, NULL}, 0, 0, 0, {0}}
#define esp_tree_runtime_v2_EventBatch_init_zero {{{NULL}, NULL}}
#define esp_tree_runtime_v2_Event_init_zero   {0, {esp_tree_runtime_v2_BridgeHeartbeat_init_zero}}
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}}
#define esp_tree_runtime_v2_RemoteStateEvent_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, esp_tree_runtime_v2_RemoteSnapshot_init_zero}
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_init_zero {false, esp_tree_runtime_v2_RemoteIdentity_init_zero, false, esp_tree_runtime_v2_RemoteRuntime_init_zero}
#define esp_tree_runtime_v2_TopologyChangedEvent_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define esp_tree_runtime_v2_BridgeHeartbeat_init_zero {{{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_CommandRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_CommandArgument_init_zero {{{NULL}, NULL}, 0, {0}}
#define esp_tree_runtime_v2_CommandResult_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _esp_tree_runtime_v2_CommandStatus_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_ConfigCommandRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0}
#define esp_tree_runtime_v2_ConfigCommandResult_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _esp_tree_runtime_v2_CommandStatus_MIN, {{NULL}, NULL}, {{NULL}, NULL}}
#define esp_tree_runtime_v2_Ping_init_zero    {0}
#define esp_tree_runtime_v2_Pong_init_zero    {0}
#define esp_tree_runtime_v2_Error_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define esp_tree_runtime_v2_AuthChallenge_server_nonce_tag 1
#define esp_tree_runtime_v2_AuthChallenge_min_version_tag 2
#define esp_tree_runtime_v2_AuthChallenge_max_version_tag 3
#define esp_tree_runtime_v2_AuthChallenge_protocol_tag 4
#define esp_tree_runtime_v2_AuthChallenge_bridge_mac_tag 5
#define esp_tree_runtime_v2_AuthResponse_client_kind_tag 1
#define esp_tree_runtime_v2_AuthResponse_client_name_tag 2
#define esp_tree_runtime_v2_AuthResponse_client_nonce_tag 3
#define esp_tree_runtime_v2_AuthResponse_hmac_sha256_tag 4
#define esp_tree_runtime_v2_AuthFailed_code_tag 1
#define esp_tree_runtime_v2_AuthFailed_message_tag 2
#define esp_tree_runtime_v2_ClientHello_request_full_snapshot_tag 1
#define esp_tree_runtime_v2_ClientHello_integration_version_tag 2
#define esp_tree_runtime_v2_ClientHello_known_remote_schemas_tag 3
#define esp_tree_runtime_v2_KnownRemoteSchema_remote_mac_tag 1
#define esp_tree_runtime_v2_KnownRemoteSchema_schema_hash_tag 2
#define esp_tree_runtime_v2_BridgeIdentity_bridge_mac_tag 1
#define esp_tree_runtime_v2_BridgeIdentity_bridge_name_tag 2
#define esp_tree_runtime_v2_BridgeIdentity_friendly_name_tag 3
#define esp_tree_runtime_v2_BridgeIdentity_network_id_tag 4
#define esp_tree_runtime_v2_BridgeIdentity_manufacturer_tag 5
#define esp_tree_runtime_v2_BridgeIdentity_model_tag 6
#define esp_tree_runtime_v2_BridgeIdentity_project_name_tag 7
#define esp_tree_runtime_v2_BridgeIdentity_project_version_tag 8
#define esp_tree_runtime_v2_BridgeIdentity_firmware_build_date_tag 9
#define esp_tree_runtime_v2_BridgeIdentity_api_server_tag 10
#define esp_tree_runtime_v2_BridgeCapabilities_supports_runtime_v2_tag 1
#define esp_tree_runtime_v2_BridgeCapabilities_supports_commands_tag 2
#define esp_tree_runtime_v2_BridgeCapabilities_supports_schema_push_tag 3
#define esp_tree_runtime_v2_BridgeCapabilities_supports_state_push_tag 4
#define esp_tree_runtime_v2_BridgeCapabilities_supports_topology_tag 5
#define esp_tree_runtime_v2_BridgeCapabilities_supports_config_commands_tag 6
#define esp_tree_runtime_v2_AuthOk_negotiated_version_tag 1
#define esp_tree_runtime_v2_AuthOk_server_name_tag 2
#define esp_tree_runtime_v2_AuthOk_bridge_tag 3
#define esp_tree_runtime_v2_AuthOk_capabilities_tag 4
#define esp_tree_runtime_v2_BridgeRuntime_online_tag 1
#define esp_tree_runtime_v2_BridgeRuntime_wifi_rssi_tag 2
#define esp_tree_runtime_v2_BridgeRuntime_uptime_s_tag 3
#define esp_tree_runtime_v2_BridgeRuntime_remote_count_tag 4
#define esp_tree_runtime_v2_FullSnapshot_bridge_tag 1
#define esp_tree_runtime_v2_FullSnapshot_bridge_runtime_tag 2
#define esp_tree_runtime_v2_FullSnapshot_remotes_tag 3
#define esp_tree_runtime_v2_FullSnapshot_snapshot_unix_ms_tag 4
#define esp_tree_runtime_v2_RemoteIdentity_remote_mac_tag 1
#define esp_tree_runtime_v2_RemoteIdentity_esphome_name_tag 2
#define esp_tree_runtime_v2_RemoteIdentity_friendly_name_tag 3
#define esp_tree_runtime_v2_RemoteIdentity_manufacturer_tag 4
#define esp_tree_runtime_v2_RemoteIdentity_model_tag 5
#define esp_tree_runtime_v2_RemoteIdentity_project_name_tag 6
#define esp_tree_runtime_v2_RemoteIdentity_project_version_tag 7
#define esp_tree_runtime_v2_RemoteIdentity_firmware_build_date_tag 8
#define esp_tree_runtime_v2_RemoteIdentity_firmware_md5_tag 9
#define esp_tree_runtime_v2_RemoteIdentity_schema_hash_tag 10
#define esp_tree_runtime_v2_RemoteIdentity_entity_count_tag 11
#define esp_tree_runtime_v2_RemoteIdentity_chip_name_tag 12
#define esp_tree_runtime_v2_RemoteIdentity_can_relay_tag 13
#define esp_tree_runtime_v2_RemoteIdentity_relay_enabled_tag 14
#define esp_tree_runtime_v2_RemoteRuntime_online_tag 1
#define esp_tree_runtime_v2_RemoteRuntime_bridge_mac_tag 2
#define esp_tree_runtime_v2_RemoteRuntime_parent_mac_tag 3
#define esp_tree_runtime_v2_RemoteRuntime_hops_to_bridge_tag 4
#define esp_tree_runtime_v2_RemoteRuntime_rssi_tag 5
#define esp_tree_runtime_v2_RemoteRuntime_offline_s_tag 6
#define esp_tree_runtime_v2_RemoteRuntime_last_seen_unix_ms_tag 7
#define esp_tree_runtime_v2_RemoteRuntime_session_id_tag 8
#define esp_tree_runtime_v2_RemoteRuntime_last_tx_counter_tag 9
#define esp_tree_runtime_v2_RemoteDescriptorSet_schema_hash_tag 1
#define esp_tree_runtime_v2_RemoteDescriptorSet_entities_tag 2
#define esp_tree_runtime_v2_RemoteSnapshot_identity_tag 1
#define esp_tree_runtime_v2_RemoteSnapshot_runtime_tag 2
#define esp_tree_runtime_v2_RemoteSnapshot_descriptor_set_tag 3
#define esp_tree_runtime_v2_RemoteSnapshot_states_tag 4
#define esp_tree_runtime_v2_Option_key_tag    1
#define esp_tree_runtime_v2_Option_label_tag  2
#define esp_tree_runtime_v2_CommandDescriptor_supported_commands_tag 1
#define esp_tree_runtime_v2_CommandDescriptor_arguments_tag 2
#define esp_tree_runtime_v2_EntityDescriptor_object_id_tag 1
#define esp_tree_runtime_v2_EntityDescriptor_platform_tag 2
#define esp_tree_runtime_v2_EntityDescriptor_friendly_name_tag 3
#define esp_tree_runtime_v2_EntityDescriptor_icon_tag 4
#define esp_tree_runtime_v2_EntityDescriptor_device_class_tag 5
#define esp_tree_runtime_v2_EntityDescriptor_state_class_tag 6
#define esp_tree_runtime_v2_EntityDescriptor_unit_of_measurement_tag 7
#define esp_tree_runtime_v2_EntityDescriptor_entity_category_tag 8
#define esp_tree_runtime_v2_EntityDescriptor_disabled_by_default_tag 9
#define esp_tree_runtime_v2_EntityDescriptor_diagnostic_tag 10
#define esp_tree_runtime_v2_EntityDescriptor_writable_tag 11
#define esp_tree_runtime_v2_EntityDescriptor_native_type_tag 12
#define esp_tree_runtime_v2_EntityDescriptor_options_json_tag 13
#define esp_tree_runtime_v2_EntityDescriptor_options_tag 14
#define esp_tree_runtime_v2_EntityDescriptor_command_tag 15
#define esp_tree_runtime_v2_ArgumentDescriptor_name_tag 1
#define esp_tree_runtime_v2_ArgumentDescriptor_value_type_tag 2
#define esp_tree_runtime_v2_ArgumentDescriptor_required_tag 3
#define esp_tree_runtime_v2_ArgumentDescriptor_min_value_tag 4
#define esp_tree_runtime_v2_ArgumentDescriptor_max_value_tag 5
#define esp_tree_runtime_v2_ArgumentDescriptor_step_tag 6
#define esp_tree_runtime_v2_EntityState_object_id_tag 1
#define esp_tree_runtime_v2_EntityState_available_tag 2
#define esp_tree_runtime_v2_EntityState_observed_unix_ms_tag 3
#define esp_tree_runtime_v2_EntityState_bool_value_tag 10
#define esp_tree_runtime_v2_EntityState_int_value_tag 11
#define esp_tree_runtime_v2_EntityState_float_value_tag 12
#define esp_tree_runtime_v2_EntityState_string_value_tag 13
#define esp_tree_runtime_v2_EntityState_bytes_value_tag 14
#define esp_tree_runtime_v2_EventBatch_events_tag 1
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_remote_mac_tag 1
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_online_tag 2
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_bridge_mac_tag 3
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_session_id_tag 4
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_tx_counter_tag 5
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_observed_unix_ms_tag 6
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_rssi_tag 7
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_hops_to_bridge_tag 8
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_reason_tag 9
#define esp_tree_runtime_v2_RemoteStateEvent_remote_mac_tag 1
#define esp_tree_runtime_v2_RemoteStateEvent_bridge_mac_tag 2
#define esp_tree_runtime_v2_RemoteStateEvent_session_id_tag 3
#define esp_tree_runtime_v2_RemoteStateEvent_tx_counter_tag 4
#define esp_tree_runtime_v2_RemoteStateEvent_states_tag 5
#define esp_tree_runtime_v2_RemoteStateEvent_observed_unix_ms_tag 6
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_remote_mac_tag 1
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_bridge_mac_tag 2
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_session_id_tag 3
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_old_schema_hash_tag 4
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_snapshot_tag 5
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_identity_tag 1
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_runtime_tag 2
#define esp_tree_runtime_v2_TopologyChangedEvent_remote_mac_tag 1
#define esp_tree_runtime_v2_TopologyChangedEvent_bridge_mac_tag 2
#define esp_tree_runtime_v2_TopologyChangedEvent_parent_mac_tag 3
#define esp_tree_runtime_v2_TopologyChangedEvent_hops_to_bridge_tag 4
#define esp_tree_runtime_v2_TopologyChangedEvent_rssi_tag 5
#define esp_tree_runtime_v2_TopologyChangedEvent_observed_unix_ms_tag 6
#define esp_tree_runtime_v2_BridgeHeartbeat_bridge_mac_tag 1
#define esp_tree_runtime_v2_BridgeHeartbeat_bridge_unix_ms_tag 2
#define esp_tree_runtime_v2_BridgeHeartbeat_uptime_s_tag 3
#define esp_tree_runtime_v2_Event_bridge_heartbeat_tag 10
#define esp_tree_runtime_v2_Event_remote_availability_tag 11
#define esp_tree_runtime_v2_Event_remote_state_tag 12
#define esp_tree_runtime_v2_Event_remote_schema_changed_tag 13
#define esp_tree_runtime_v2_Event_remote_metadata_changed_tag 14
#define esp_tree_runtime_v2_Event_topology_changed_tag 15
#define esp_tree_runtime_v2_CommandRequest_remote_mac_tag 1
#define esp_tree_runtime_v2_CommandRequest_object_id_tag 2
#define esp_tree_runtime_v2_CommandRequest_command_tag 3
#define esp_tree_runtime_v2_CommandRequest_args_tag 4
#define esp_tree_runtime_v2_CommandArgument_name_tag 1
#define esp_tree_runtime_v2_CommandArgument_bool_value_tag 10
#define esp_tree_runtime_v2_CommandArgument_int_value_tag 11
#define esp_tree_runtime_v2_CommandArgument_float_value_tag 12
#define esp_tree_runtime_v2_CommandArgument_string_value_tag 13
#define esp_tree_runtime_v2_CommandResult_remote_mac_tag 1
#define esp_tree_runtime_v2_CommandResult_object_id_tag 2
#define esp_tree_runtime_v2_CommandResult_command_tag 3
#define esp_tree_runtime_v2_CommandResult_bridge_mac_tag 4
#define esp_tree_runtime_v2_CommandResult_session_id_tag 5
#define esp_tree_runtime_v2_CommandResult_status_tag 6
#define esp_tree_runtime_v2_CommandResult_error_code_tag 7
#define esp_tree_runtime_v2_CommandResult_error_message_tag 8
#define esp_tree_runtime_v2_ConfigCommandRequest_remote_mac_tag 1
#define esp_tree_runtime_v2_ConfigCommandRequest_command_tag 2
#define esp_tree_runtime_v2_ConfigCommandRequest_interval_seconds_tag 3
#define esp_tree_runtime_v2_ConfigCommandRequest_parent_mac_tag 4
#define esp_tree_runtime_v2_ConfigCommandRequest_clear_parent_tag 5
#define esp_tree_runtime_v2_ConfigCommandRequest_relay_enable_tag 6
#define esp_tree_runtime_v2_ConfigCommandResult_remote_mac_tag 1
#define esp_tree_runtime_v2_ConfigCommandResult_command_tag 2
#define esp_tree_runtime_v2_ConfigCommandResult_bridge_mac_tag 3
#define esp_tree_runtime_v2_ConfigCommandResult_session_id_tag 4
#define esp_tree_runtime_v2_ConfigCommandResult_status_tag 5
#define esp_tree_runtime_v2_ConfigCommandResult_error_code_tag 6
#define esp_tree_runtime_v2_ConfigCommandResult_error_message_tag 7
#define esp_tree_runtime_v2_Ping_monotonic_ms_tag 1
#define esp_tree_runtime_v2_Pong_monotonic_ms_tag 1
#define esp_tree_runtime_v2_Error_code_tag    1
#define esp_tree_runtime_v2_Error_message_tag 2
#define esp_tree_runtime_v2_Envelope_request_id_tag 1
#define esp_tree_runtime_v2_Envelope_api_version_tag 2
#define esp_tree_runtime_v2_Envelope_auth_challenge_tag 10
#define esp_tree_runtime_v2_Envelope_auth_response_tag 11
#define esp_tree_runtime_v2_Envelope_auth_ok_tag 12
#define esp_tree_runtime_v2_Envelope_auth_failed_tag 13
#define esp_tree_runtime_v2_Envelope_client_hello_tag 14
#define esp_tree_runtime_v2_Envelope_full_snapshot_tag 15
#define esp_tree_runtime_v2_Envelope_event_batch_tag 16
#define esp_tree_runtime_v2_Envelope_command_request_tag 17
#define esp_tree_runtime_v2_Envelope_command_result_tag 18
#define esp_tree_runtime_v2_Envelope_config_command_request_tag 19
#define esp_tree_runtime_v2_Envelope_config_command_result_tag 20
#define esp_tree_runtime_v2_Envelope_ping_tag 21
#define esp_tree_runtime_v2_Envelope_pong_tag 22
#define esp_tree_runtime_v2_Envelope_error_tag 99

/* Struct field encoding specification for nanopb */
#define esp_tree_runtime_v2_Envelope_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   request_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   api_version,       2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,auth_challenge,msg.auth_challenge),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,auth_response,msg.auth_response),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,auth_ok,msg.auth_ok),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,auth_failed,msg.auth_failed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,client_hello,msg.client_hello),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,full_snapshot,msg.full_snapshot),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,event_batch,msg.event_batch),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,command_request,msg.command_request),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,command_result,msg.command_result),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,config_command_request,msg.config_command_request),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,config_command_result,msg.config_command_result),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,ping,msg.ping),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,pong,msg.pong),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,error,msg.error),  99)
#define esp_tree_runtime_v2_Envelope_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_Envelope_DEFAULT NULL
#define esp_tree_runtime_v2_Envelope_msg_auth_challenge_MSGTYPE esp_tree_runtime_v2_AuthChallenge
#define esp_tree_runtime_v2_Envelope_msg_auth_response_MSGTYPE esp_tree_runtime_v2_AuthResponse
#define esp_tree_runtime_v2_Envelope_msg_auth_ok_MSGTYPE esp_tree_runtime_v2_AuthOk
#define esp_tree_runtime_v2_Envelope_msg_auth_failed_MSGTYPE esp_tree_runtime_v2_AuthFailed
#define esp_tree_runtime_v2_Envelope_msg_client_hello_MSGTYPE esp_tree_runtime_v2_ClientHello
#define esp_tree_runtime_v2_Envelope_msg_full_snapshot_MSGTYPE esp_tree_runtime_v2_FullSnapshot
#define esp_tree_runtime_v2_Envelope_msg_event_batch_MSGTYPE esp_tree_runtime_v2_EventBatch
#define esp_tree_runtime_v2_Envelope_msg_command_request_MSGTYPE esp_tree_runtime_v2_CommandRequest
#define esp_tree_runtime_v2_Envelope_msg_command_result_MSGTYPE esp_tree_runtime_v2_CommandResult
#define esp_tree_runtime_v2_Envelope_msg_config_command_request_MSGTYPE esp_tree_runtime_v2_ConfigCommandRequest
#define esp_tree_runtime_v2_Envelope_msg_config_command_result_MSGTYPE esp_tree_runtime_v2_ConfigCommandResult
#define esp_tree_runtime_v2_Envelope_msg_ping_MSGTYPE esp_tree_runtime_v2_Ping
#define esp_tree_runtime_v2_Envelope_msg_pong_MSGTYPE esp_tree_runtime_v2_Pong
#define esp_tree_runtime_v2_Envelope_msg_error_MSGTYPE esp_tree_runtime_v2_Error

#define esp_tree_runtime_v2_AuthChallenge_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    server_nonce,      1) \
X(a, STATIC,   SINGULAR, UINT32,   min_version,       2) \
X(a, STATIC,   SINGULAR, UINT32,   max_version,       3) \
X(a, CALLBACK, SINGULAR, STRING,   protocol,          4) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        5)
#define esp_tree_runtime_v2_AuthChallenge_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_AuthChallenge_DEFAULT NULL

#define esp_tree_runtime_v2_AuthResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   client_kind,       1) \
X(a, CALLBACK, SINGULAR, STRING,   client_name,       2) \
X(a, CALLBACK, SINGULAR, BYTES,    client_nonce,      3) \
X(a, CALLBACK, SINGULAR, BYTES,    hmac_sha256,       4)
#define esp_tree_runtime_v2_AuthResponse_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_AuthResponse_DEFAULT NULL

#define esp_tree_runtime_v2_AuthOk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   negotiated_version,   1) \
X(a, CALLBACK, SINGULAR, STRING,   server_name,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  capabilities,      4)
#define esp_tree_runtime_v2_AuthOk_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_AuthOk_DEFAULT NULL
#define esp_tree_runtime_v2_AuthOk_bridge_MSGTYPE esp_tree_runtime_v2_BridgeIdentity
#define esp_tree_runtime_v2_AuthOk_capabilities_MSGTYPE esp_tree_runtime_v2_BridgeCapabilities

#define esp_tree_runtime_v2_AuthFailed_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define esp_tree_runtime_v2_AuthFailed_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_AuthFailed_DEFAULT NULL

#define esp_tree_runtime_v2_ClientHello_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     request_full_snapshot,   1) \
X(a, CALLBACK, SINGULAR, STRING,   integration_version,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  known_remote_schemas,   3)
#define esp_tree_runtime_v2_ClientHello_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_ClientHello_DEFAULT NULL
#define esp_tree_runtime_v2_ClientHello_known_remote_schemas_MSGTYPE esp_tree_runtime_v2_KnownRemoteSchema

#define esp_tree_runtime_v2_KnownRemoteSchema_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   schema_hash,       2)
#define esp_tree_runtime_v2_KnownRemoteSchema_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_KnownRemoteSchema_DEFAULT NULL

#define esp_tree_runtime_v2_FullSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bridge_runtime,    2) \
X(a, CALLBACK, REPEATED, MESSAGE,  remotes,           3) \
X(a, STATIC,   SINGULAR, UINT64,   snapshot_unix_ms,   4)
#define esp_tree_runtime_v2_FullSnapshot_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_FullSnapshot_DEFAULT NULL
#define esp_tree_runtime_v2_FullSnapshot_bridge_MSGTYPE esp_tree_runtime_v2_BridgeIdentity
#define esp_tree_runtime_v2_FullSnapshot_bridge_runtime_MSGTYPE esp_tree_runtime_v2_BridgeRuntime
#define esp_tree_runtime_v2_FullSnapshot_remotes_MSGTYPE esp_tree_runtime_v2_RemoteSnapshot

#define esp_tree_runtime_v2_BridgeIdentity_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_name,       2) \
X(a, CALLBACK, SINGULAR, STRING,   friendly_name,     3) \
X(a, CALLBACK, SINGULAR, STRING,   network_id,        4) \
X(a, CALLBACK, SINGULAR, STRING,   manufacturer,      5) \
X(a, CALLBACK, SINGULAR, STRING,   model,             6) \
X(a, CALLBACK, SINGULAR, STRING,   project_name,      7) \
X(a, CALLBACK, SINGULAR, STRING,   project_version,   8) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_build_date,   9) \
X(a, CALLBACK, SINGULAR, STRING,   api_server,       10)
#define esp_tree_runtime_v2_BridgeIdentity_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_BridgeIdentity_DEFAULT NULL

#define esp_tree_runtime_v2_BridgeCapabilities_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     supports_runtime_v2,   1) \
X(a, STATIC,   SINGULAR, BOOL,     supports_commands,   2) \
X(a, STATIC,   SINGULAR, BOOL,     supports_schema_push,   3) \
X(a, STATIC,   SINGULAR, BOOL,     supports_state_push,   4) \
X(a, STATIC,   SINGULAR, BOOL,     supports_topology,   5) \
X(a, STATIC,   SINGULAR, BOOL,     supports_config_commands,   6)
#define esp_tree_runtime_v2_BridgeCapabilities_CALLBACK NULL
#define esp_tree_runtime_v2_BridgeCapabilities_DEFAULT NULL

#define esp_tree_runtime_v2_BridgeRuntime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     online,            1) \
X(a, STATIC,   SINGULAR, SINT32,   wifi_rssi,         2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          3) \
X(a, STATIC,   SINGULAR, UINT32,   remote_count,      4)
#define esp_tree_runtime_v2_BridgeRuntime_CALLBACK NULL
#define esp_tree_runtime_v2_BridgeRuntime_DEFAULT NULL

#define esp_tree_runtime_v2_RemoteSnapshot_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  identity,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  runtime,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  descriptor_set,    3) \
X(a, CALLBACK, REPEATED, MESSAGE,  states,            4)
#define esp_tree_runtime_v2_RemoteSnapshot_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteSnapshot_DEFAULT NULL
#define esp_tree_runtime_v2_RemoteSnapshot_identity_MSGTYPE esp_tree_runtime_v2_RemoteIdentity
#define esp_tree_runtime_v2_RemoteSnapshot_runtime_MSGTYPE esp_tree_runtime_v2_RemoteRuntime
#define esp_tree_runtime_v2_RemoteSnapshot_descriptor_set_MSGTYPE esp_tree_runtime_v2_RemoteDescriptorSet
#define esp_tree_runtime_v2_RemoteSnapshot_states_MSGTYPE esp_tree_runtime_v2_EntityState

#define esp_tree_runtime_v2_RemoteIdentity_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   esphome_name,      2) \
X(a, CALLBACK, SINGULAR, STRING,   friendly_name,     3) \
X(a, CALLBACK, SINGULAR, STRING,   manufacturer,      4) \
X(a, CALLBACK, SINGULAR, STRING,   model,             5) \
X(a, CALLBACK, SINGULAR, STRING,   project_name,      6) \
X(a, CALLBACK, SINGULAR, STRING,   project_version,   7) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_build_date,   8) \
X(a, CALLBACK, SINGULAR, STRING,   firmware_md5,      9) \
X(a, CALLBACK, SINGULAR, STRING,   schema_hash,      10) \
X(a, STATIC,   SINGULAR, UINT32,   entity_count,     11) \
X(a, CALLBACK, SINGULAR, STRING,   chip_name,        12) \
X(a, STATIC,   SINGULAR, BOOL,     can_relay,        13) \
X(a, STATIC,   SINGULAR, BOOL,     relay_enabled,    14)
#define esp_tree_runtime_v2_RemoteIdentity_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteIdentity_DEFAULT NULL

#define esp_tree_runtime_v2_RemoteRuntime_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     online,            1) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        2) \
X(a, CALLBACK, SINGULAR, STRING,   parent_mac,        3) \
X(a, STATIC,   SINGULAR, UINT32,   hops_to_bridge,    4) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              5) \
X(a, STATIC,   SINGULAR, UINT32,   offline_s,         6) \
X(a, STATIC,   SINGULAR, UINT64,   last_seen_unix_ms,   7) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        8) \
X(a, STATIC,   SINGULAR, UINT32,   last_tx_counter,   9)
#define esp_tree_runtime_v2_RemoteRuntime_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteRuntime_DEFAULT NULL

#define esp_tree_runtime_v2_RemoteDescriptorSet_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   schema_hash,       1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entities,          2)
#define esp_tree_runtime_v2_RemoteDescriptorSet_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteDescriptorSet_DEFAULT NULL
#define esp_tree_runtime_v2_RemoteDescriptorSet_entities_MSGTYPE esp_tree_runtime_v2_EntityDescriptor

#define esp_tree_runtime_v2_EntityDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   object_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   platform,          2) \
X(a, CALLBACK, SINGULAR, STRING,   friendly_name,     3) \
X(a, CALLBACK, SINGULAR, STRING,   icon,              4) \
X(a, CALLBACK, SINGULAR, STRING,   device_class,      5) \
X(a, CALLBACK, SINGULAR, STRING,   state_class,       6) \
X(a, CALLBACK, SINGULAR, STRING,   unit_of_measurement,   7) \
X(a, CALLBACK, SINGULAR, STRING,   entity_category,   8) \
X(a, STATIC,   SINGULAR, BOOL,     disabled_by_default,   9) \
X(a, STATIC,   SINGULAR, BOOL,     diagnostic,       10) \
X(a, STATIC,   SINGULAR, BOOL,     writable,         11) \
X(a, CALLBACK, SINGULAR, STRING,   native_type,      12) \
X(a, CALLBACK, SINGULAR, STRING,   options_json,     13) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,          14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,          15)
#define esp_tree_runtime_v2_EntityDescriptor_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_EntityDescriptor_DEFAULT NULL
#define esp_tree_runtime_v2_EntityDescriptor_options_MSGTYPE esp_tree_runtime_v2_Option
#define esp_tree_runtime_v2_EntityDescriptor_command_MSGTYPE esp_tree_runtime_v2_CommandDescriptor

#define esp_tree_runtime_v2_Option_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   label,             2)
#define esp_tree_runtime_v2_Option_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_Option_DEFAULT NULL

#define esp_tree_runtime_v2_CommandDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   supported_commands,   1) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2)
#define esp_tree_runtime_v2_CommandDescriptor_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_CommandDescriptor_DEFAULT NULL
#define esp_tree_runtime_v2_CommandDescriptor_arguments_MSGTYPE esp_tree_runtime_v2_ArgumentDescriptor

#define esp_tree_runtime_v2_ArgumentDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   value_type,        2) \
X(a, STATIC,   SINGULAR, BOOL,     required,          3) \
X(a, STATIC,   SINGULAR, DOUBLE,   min_value,         4) \
X(a, STATIC,   SINGULAR, DOUBLE,   max_value,         5) \
X(a, STATIC,   SINGULAR, DOUBLE,   step,              6)
#define esp_tree_runtime_v2_ArgumentDescriptor_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_ArgumentDescriptor_DEFAULT NULL

#define esp_tree_runtime_v2_EntityState_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   object_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     available,         2) \
X(a, STATIC,   SINGULAR, UINT64,   observed_unix_ms,   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),  10) \
X(a, STATIC,   ONEOF,    SINT64,   (value,int_value,value.int_value),  11) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,float_value,value.float_value),  12) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),  13) \
X(a, CALLBACK, ONEOF,    BYTES,    (value,bytes_value,value.bytes_value),  14)
#define esp_tree_runtime_v2_EntityState_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_EntityState_DEFAULT NULL

#define esp_tree_runtime_v2_EventBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  events,            1)
#define esp_tree_runtime_v2_EventBatch_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_EventBatch_DEFAULT NULL
#define esp_tree_runtime_v2_EventBatch_events_MSGTYPE esp_tree_runtime_v2_Event

#define esp_tree_runtime_v2_Event_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,bridge_heartbeat,kind.bridge_heartbeat),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,remote_availability,kind.remote_availability),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,remote_state,kind.remote_state),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,remote_schema_changed,kind.remote_schema_changed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,remote_metadata_changed,kind.remote_metadata_changed),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,topology_changed,kind.topology_changed),  15)
#define esp_tree_runtime_v2_Event_CALLBACK NULL
#define esp_tree_runtime_v2_Event_DEFAULT NULL
#define esp_tree_runtime_v2_Event_kind_bridge_heartbeat_MSGTYPE esp_tree_runtime_v2_BridgeHeartbeat
#define esp_tree_runtime_v2_Event_kind_remote_availability_MSGTYPE esp_tree_runtime_v2_RemoteAvailabilityEvent
#define esp_tree_runtime_v2_Event_kind_remote_state_MSGTYPE esp_tree_runtime_v2_RemoteStateEvent
#define esp_tree_runtime_v2_Event_kind_remote_schema_changed_MSGTYPE esp_tree_runtime_v2_RemoteSchemaChangedEvent
#define esp_tree_runtime_v2_Event_kind_remote_metadata_changed_MSGTYPE esp_tree_runtime_v2_RemoteMetadataChangedEvent
#define esp_tree_runtime_v2_Event_kind_topology_changed_MSGTYPE esp_tree_runtime_v2_TopologyChangedEvent

#define esp_tree_runtime_v2_RemoteAvailabilityEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, STATIC,   SINGULAR, BOOL,     online,            2) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        3) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        4) \
X(a, STATIC,   SINGULAR, UINT32,   tx_counter,        5) \
X(a, STATIC,   SINGULAR, UINT64,   observed_unix_ms,   6) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              7) \
X(a, STATIC,   SINGULAR, UINT32,   hops_to_bridge,    8) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            9)
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_DEFAULT NULL

#define esp_tree_runtime_v2_RemoteStateEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        2) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        3) \
X(a, STATIC,   SINGULAR, UINT32,   tx_counter,        4) \
X(a, CALLBACK, REPEATED, MESSAGE,  states,            5) \
X(a, STATIC,   SINGULAR, UINT64,   observed_unix_ms,   6)
#define esp_tree_runtime_v2_RemoteStateEvent_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteStateEvent_DEFAULT NULL
#define esp_tree_runtime_v2_RemoteStateEvent_states_MSGTYPE esp_tree_runtime_v2_EntityState

#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        2) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        3) \
X(a, CALLBACK, SINGULAR, STRING,   old_schema_hash,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  snapshot,          5)
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_DEFAULT NULL
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_snapshot_MSGTYPE esp_tree_runtime_v2_RemoteSnapshot

#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  identity,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  runtime,           2)
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_CALLBACK NULL
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_DEFAULT NULL
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_identity_MSGTYPE esp_tree_runtime_v2_RemoteIdentity
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_runtime_MSGTYPE esp_tree_runtime_v2_RemoteRuntime

#define esp_tree_runtime_v2_TopologyChangedEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        2) \
X(a, CALLBACK, SINGULAR, STRING,   parent_mac,        3) \
X(a, STATIC,   SINGULAR, UINT32,   hops_to_bridge,    4) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              5) \
X(a, STATIC,   SINGULAR, UINT64,   observed_unix_ms,   6)
#define esp_tree_runtime_v2_TopologyChangedEvent_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_TopologyChangedEvent_DEFAULT NULL

#define esp_tree_runtime_v2_BridgeHeartbeat_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        1) \
X(a, STATIC,   SINGULAR, UINT64,   bridge_unix_ms,    2) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          3)
#define esp_tree_runtime_v2_BridgeHeartbeat_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_BridgeHeartbeat_DEFAULT NULL

#define esp_tree_runtime_v2_CommandRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   object_id,         2) \
X(a, CALLBACK, SINGULAR, STRING,   command,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  args,              4)
#define esp_tree_runtime_v2_CommandRequest_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_CommandRequest_DEFAULT NULL
#define esp_tree_runtime_v2_CommandRequest_args_MSGTYPE esp_tree_runtime_v2_CommandArgument

#define esp_tree_runtime_v2_CommandArgument_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),  10) \
X(a, STATIC,   ONEOF,    SINT64,   (value,int_value,value.int_value),  11) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,float_value,value.float_value),  12) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),  13)
#define esp_tree_runtime_v2_CommandArgument_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_CommandArgument_DEFAULT NULL

#define esp_tree_runtime_v2_CommandResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   object_id,         2) \
X(a, CALLBACK, SINGULAR, STRING,   command,           3) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        4) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        5) \
X(a, STATIC,   SINGULAR, UENUM,    status,            6) \
X(a, CALLBACK, SINGULAR, STRING,   error_code,        7) \
X(a, CALLBACK, SINGULAR, STRING,   error_message,     8)
#define esp_tree_runtime_v2_CommandResult_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_CommandResult_DEFAULT NULL

#define esp_tree_runtime_v2_ConfigCommandRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   command,           2) \
X(a, STATIC,   SINGULAR, UINT32,   interval_seconds,   3) \
X(a, CALLBACK, SINGULAR, STRING,   parent_mac,        4) \
X(a, STATIC,   SINGULAR, BOOL,     clear_parent,      5) \
X(a, STATIC,   SINGULAR, BOOL,     relay_enable,      6)
#define esp_tree_runtime_v2_ConfigCommandRequest_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_ConfigCommandRequest_DEFAULT NULL

#define esp_tree_runtime_v2_ConfigCommandResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   remote_mac,        1) \
X(a, CALLBACK, SINGULAR, STRING,   command,           2) \
X(a, CALLBACK, SINGULAR, STRING,   bridge_mac,        3) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        4) \
X(a, STATIC,   SINGULAR, UENUM,    status,            5) \
X(a, CALLBACK, SINGULAR, STRING,   error_code,        6) \
X(a, CALLBACK, SINGULAR, STRING,   error_message,     7)
#define esp_tree_runtime_v2_ConfigCommandResult_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_ConfigCommandResult_DEFAULT NULL

#define esp_tree_runtime_v2_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   monotonic_ms,      1)
#define esp_tree_runtime_v2_Ping_CALLBACK NULL
#define esp_tree_runtime_v2_Ping_DEFAULT NULL

#define esp_tree_runtime_v2_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   monotonic_ms,      1)
#define esp_tree_runtime_v2_Pong_CALLBACK NULL
#define esp_tree_runtime_v2_Pong_DEFAULT NULL

#define esp_tree_runtime_v2_Error_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define esp_tree_runtime_v2_Error_CALLBACK pb_default_field_callback
#define esp_tree_runtime_v2_Error_DEFAULT NULL

extern const pb_msgdesc_t esp_tree_runtime_v2_Envelope_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_AuthChallenge_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_AuthResponse_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_AuthOk_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_AuthFailed_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_ClientHello_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_KnownRemoteSchema_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_FullSnapshot_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_BridgeIdentity_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_BridgeCapabilities_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_BridgeRuntime_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteSnapshot_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteIdentity_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteRuntime_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteDescriptorSet_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_EntityDescriptor_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_Option_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_CommandDescriptor_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_ArgumentDescriptor_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_EntityState_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_EventBatch_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_Event_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteAvailabilityEvent_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteStateEvent_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteSchemaChangedEvent_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_RemoteMetadataChangedEvent_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_TopologyChangedEvent_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_BridgeHeartbeat_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_CommandRequest_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_CommandArgument_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_CommandResult_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_ConfigCommandRequest_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_ConfigCommandResult_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_Ping_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_Pong_msg;
extern const pb_msgdesc_t esp_tree_runtime_v2_Error_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define esp_tree_runtime_v2_Envelope_fields &esp_tree_runtime_v2_Envelope_msg
#define esp_tree_runtime_v2_AuthChallenge_fields &esp_tree_runtime_v2_AuthChallenge_msg
#define esp_tree_runtime_v2_AuthResponse_fields &esp_tree_runtime_v2_AuthResponse_msg
#define esp_tree_runtime_v2_AuthOk_fields &esp_tree_runtime_v2_AuthOk_msg
#define esp_tree_runtime_v2_AuthFailed_fields &esp_tree_runtime_v2_AuthFailed_msg
#define esp_tree_runtime_v2_ClientHello_fields &esp_tree_runtime_v2_ClientHello_msg
#define esp_tree_runtime_v2_KnownRemoteSchema_fields &esp_tree_runtime_v2_KnownRemoteSchema_msg
#define esp_tree_runtime_v2_FullSnapshot_fields &esp_tree_runtime_v2_FullSnapshot_msg
#define esp_tree_runtime_v2_BridgeIdentity_fields &esp_tree_runtime_v2_BridgeIdentity_msg
#define esp_tree_runtime_v2_BridgeCapabilities_fields &esp_tree_runtime_v2_BridgeCapabilities_msg
#define esp_tree_runtime_v2_BridgeRuntime_fields &esp_tree_runtime_v2_BridgeRuntime_msg
#define esp_tree_runtime_v2_RemoteSnapshot_fields &esp_tree_runtime_v2_RemoteSnapshot_msg
#define esp_tree_runtime_v2_RemoteIdentity_fields &esp_tree_runtime_v2_RemoteIdentity_msg
#define esp_tree_runtime_v2_RemoteRuntime_fields &esp_tree_runtime_v2_RemoteRuntime_msg
#define esp_tree_runtime_v2_RemoteDescriptorSet_fields &esp_tree_runtime_v2_RemoteDescriptorSet_msg
#define esp_tree_runtime_v2_EntityDescriptor_fields &esp_tree_runtime_v2_EntityDescriptor_msg
#define esp_tree_runtime_v2_Option_fields &esp_tree_runtime_v2_Option_msg
#define esp_tree_runtime_v2_CommandDescriptor_fields &esp_tree_runtime_v2_CommandDescriptor_msg
#define esp_tree_runtime_v2_ArgumentDescriptor_fields &esp_tree_runtime_v2_ArgumentDescriptor_msg
#define esp_tree_runtime_v2_EntityState_fields &esp_tree_runtime_v2_EntityState_msg
#define esp_tree_runtime_v2_EventBatch_fields &esp_tree_runtime_v2_EventBatch_msg
#define esp_tree_runtime_v2_Event_fields &esp_tree_runtime_v2_Event_msg
#define esp_tree_runtime_v2_RemoteAvailabilityEvent_fields &esp_tree_runtime_v2_RemoteAvailabilityEvent_msg
#define esp_tree_runtime_v2_RemoteStateEvent_fields &esp_tree_runtime_v2_RemoteStateEvent_msg
#define esp_tree_runtime_v2_RemoteSchemaChangedEvent_fields &esp_tree_runtime_v2_RemoteSchemaChangedEvent_msg
#define esp_tree_runtime_v2_RemoteMetadataChangedEvent_fields &esp_tree_runtime_v2_RemoteMetadataChangedEvent_msg
#define esp_tree_runtime_v2_TopologyChangedEvent_fields &esp_tree_runtime_v2_TopologyChangedEvent_msg
#define esp_tree_runtime_v2_BridgeHeartbeat_fields &esp_tree_runtime_v2_BridgeHeartbeat_msg
#define esp_tree_runtime_v2_CommandRequest_fields &esp_tree_runtime_v2_CommandRequest_msg
#define esp_tree_runtime_v2_CommandArgument_fields &esp_tree_runtime_v2_CommandArgument_msg
#define esp_tree_runtime_v2_CommandResult_fields &esp_tree_runtime_v2_CommandResult_msg
#define esp_tree_runtime_v2_ConfigCommandRequest_fields &esp_tree_runtime_v2_ConfigCommandRequest_msg
#define esp_tree_runtime_v2_ConfigCommandResult_fields &esp_tree_runtime_v2_ConfigCommandResult_msg
#define esp_tree_runtime_v2_Ping_fields &esp_tree_runtime_v2_Ping_msg
#define esp_tree_runtime_v2_Pong_fields &esp_tree_runtime_v2_Pong_msg
#define esp_tree_runtime_v2_Error_fields &esp_tree_runtime_v2_Error_msg

/* Maximum encoded size of messages (where known) */
/* esp_tree_runtime_v2_Envelope_size depends on runtime parameters */
/* esp_tree_runtime_v2_AuthChallenge_size depends on runtime parameters */
/* esp_tree_runtime_v2_AuthResponse_size depends on runtime parameters */
/* esp_tree_runtime_v2_AuthOk_size depends on runtime parameters */
/* esp_tree_runtime_v2_AuthFailed_size depends on runtime parameters */
/* esp_tree_runtime_v2_ClientHello_size depends on runtime parameters */
/* esp_tree_runtime_v2_KnownRemoteSchema_size depends on runtime parameters */
/* esp_tree_runtime_v2_FullSnapshot_size depends on runtime parameters */
/* esp_tree_runtime_v2_BridgeIdentity_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteSnapshot_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteIdentity_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteRuntime_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteDescriptorSet_size depends on runtime parameters */
/* esp_tree_runtime_v2_EntityDescriptor_size depends on runtime parameters */
/* esp_tree_runtime_v2_Option_size depends on runtime parameters */
/* esp_tree_runtime_v2_CommandDescriptor_size depends on runtime parameters */
/* esp_tree_runtime_v2_ArgumentDescriptor_size depends on runtime parameters */
/* esp_tree_runtime_v2_EntityState_size depends on runtime parameters */
/* esp_tree_runtime_v2_EventBatch_size depends on runtime parameters */
/* esp_tree_runtime_v2_Event_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteAvailabilityEvent_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteStateEvent_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteSchemaChangedEvent_size depends on runtime parameters */
/* esp_tree_runtime_v2_RemoteMetadataChangedEvent_size depends on runtime parameters */
/* esp_tree_runtime_v2_TopologyChangedEvent_size depends on runtime parameters */
/* esp_tree_runtime_v2_BridgeHeartbeat_size depends on runtime parameters */
/* esp_tree_runtime_v2_CommandRequest_size depends on runtime parameters */
/* esp_tree_runtime_v2_CommandArgument_size depends on runtime parameters */
/* esp_tree_runtime_v2_CommandResult_size depends on runtime parameters */
/* esp_tree_runtime_v2_ConfigCommandRequest_size depends on runtime parameters */
/* esp_tree_runtime_v2_ConfigCommandResult_size depends on runtime parameters */
/* esp_tree_runtime_v2_Error_size depends on runtime parameters */
#define ESP_TREE_RUNTIME_V2_ESP_TREE_RUNTIME_PB_H_MAX_SIZE esp_tree_runtime_v2_BridgeRuntime_size
#define esp_tree_runtime_v2_BridgeCapabilities_size 12
#define esp_tree_runtime_v2_BridgeRuntime_size 20
#define esp_tree_runtime_v2_Ping_size         11
#define esp_tree_runtime_v2_Pong_size         11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
