# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: espnow_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'espnow_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65spnow_bridge.proto\x12\tespnow_lr\"[\n\x0b\x42ridgeHello\x12\x12\n\nbridge_mac\x18\x01 \x01(\x0c\x12\x11\n\tmax_peers\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x14\n\x0cmax_inflight\x18\x04 \x01(\r\"k\n\nRadioFrame\x12\x0f\n\x07src_mac\x18\x01 \x01(\x0c\x12\x11\n\traw_frame\x18\x02 \x01(\x0c\x12\x15\n\rpsk_tag_valid\x18\x03 \x01(\x08\x12\x0c\n\x04rssi\x18\x04 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\r\"<\n\tRadioSend\x12\x0f\n\x07\x64st_mac\x18\x01 \x01(\x0c\x12\x11\n\traw_frame\x18\x02 \x01(\x0c\x12\x0b\n\x03seq\x18\x03 \x01(\r\"9\n\nSendResult\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"v\n\x0c\x42ridgeStatus\x12\x11\n\twifi_rssi\x18\x01 \x01(\x05\x12\x10\n\x08uptime_s\x18\x02 \x01(\r\x12\x11\n\tfree_heap\x18\x03 \x01(\r\x12\x17\n\x0fpeers_connected\x18\x04 \x01(\r\x12\x15\n\rrx_queue_fill\x18\x05 \x01(\r\"\xe5\x01\n\rBridgeMessage\x12\'\n\x05hello\x18\x01 \x01(\x0b\x32\x16.esp_tree.BridgeHelloH\x00\x12&\n\x05\x66rame\x18\x02 \x01(\x0b\x32\x15.esp_tree.RadioFrameH\x00\x12$\n\x04send\x18\x03 \x01(\x0b\x32\x14.esp_tree.RadioSendH\x00\x12\'\n\x06result\x18\x04 \x01(\x0b\x32\x15.esp_tree.SendResultH\x00\x12)\n\x06status\x18\x05 \x01(\x0b\x32\x17.esp_tree.BridgeStatusH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'espnow_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRIDGEHELLO']._serialized_start=34
  _globals['_BRIDGEHELLO']._serialized_end=125
  _globals['_RADIOFRAME']._serialized_start=127
  _globals['_RADIOFRAME']._serialized_end=234
  _globals['_RADIOSEND']._serialized_start=236
  _globals['_RADIOSEND']._serialized_end=296
  _globals['_SENDRESULT']._serialized_start=298
  _globals['_SENDRESULT']._serialized_end=355
  _globals['_BRIDGESTATUS']._serialized_start=357
  _globals['_BRIDGESTATUS']._serialized_end=475
  _globals['_BRIDGEMESSAGE']._serialized_start=478
  _globals['_BRIDGEMESSAGE']._serialized_end=707
# @@protoc_insertion_point(module_scope)
