[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
build_flags =
    -Isrc
    -I/compat
    -I/components
    -I/components/espnow_82xx_remote
    -I/components/esp_tree_common
    -include src/compat_overrides.h
    -DARDUINO_ARCH_ESP8266
    -DUSE_ESP8266
board_build.ldscript = eagle.flash.1m.ld
board_build.flash_size = 1MB
board_build.maximum_size = 1048576
board_upload.flash_size = 1MB
lib_ldf_mode = chain
lib_compat_mode = strict
lib_ignore =
    RPAsyncTCP
    ESP Async WebServer
extra_scripts = pre:copy_libs.py
