name: ESP Tree
version: 0.1.150
slug: esp-tree
description: Manage ESP-NOW LR remotes through an ESP32 bridge
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
panel_icon: mdi:radio-tower
panel_title: ESP Tree
startup: services
host_network: true
homeassistant_api: true
hassio_api: true
discovery:
  - esp_tree
init: false
map:
  - type: homeassistant_config
    read_only: false
options:
  firmware_retention_days: 7
  scan_subnets: ""
schema:
  firmware_retention_days: int
  scan_subnets: str
