name: Build add-on

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: Build ESPHome ESPNow Tree add-on
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target esphome-espnow-tree-ha \
            --test \
            --build-arg GIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg GIT_DATE=$(git log -1 --format=%cI)
